// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "lobby.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(960, 635, "Lobby");
    w = o;
    { new Fl_Box(0, 0, 960, 640);
    } // Fl_Box* o
    { Fl_Scroll* o = new Fl_Scroll(18, 18, 652, 557);
      o->box(FL_GTK_DOWN_BOX);
      o->color(FL_FOREGROUND_COLOR);
      { Fl_Scrollbar* o = new Fl_Scrollbar(634, 19, 34, 553);
        o->box(FL_GTK_DOWN_BOX);
        o->color((Fl_Color)34);
      } // Fl_Scrollbar* o
      { Fl_Group* o = new Fl_Group(33, 34, 589, 142);
        o->box(FL_GLEAM_THIN_UP_BOX);
        o->color((Fl_Color)36);
        { Fl_Output* o = new Fl_Output(51, 54, 320, 35);
          o->box(FL_NO_BOX);
          o->textfont(1);
          o->textsize(24);
          o->textcolor((Fl_Color)26);
        } // Fl_Output* o
        { Fl_Output* o = new Fl_Output(175, 89, 127, 35, "Dealer ID      ");
          o->box(FL_NO_BOX);
          o->labelfont(1);
          o->labelsize(16);
          o->labelcolor((Fl_Color)26);
          o->textsize(16);
          o->textcolor((Fl_Color)26);
        } // Fl_Output* o
        { Fl_Output* o = new Fl_Output(176, 117, 127, 35, "Player Count ");
          o->box(FL_NO_BOX);
          o->labelfont(1);
          o->labelsize(16);
          o->labelcolor((Fl_Color)26);
          o->textsize(16);
          o->textcolor((Fl_Color)26);
        } // Fl_Output* o
        { Fl_Output* o = new Fl_Output(497, 88, 120, 35, "Shoe size     ");
          o->box(FL_NO_BOX);
          o->labelfont(1);
          o->labelsize(16);
          o->labelcolor((Fl_Color)26);
          o->textsize(16);
          o->textcolor((Fl_Color)26);
        } // Fl_Output* o
        { Fl_Output* o = new Fl_Output(498, 116, 119, 35, "Min-Max bet ");
          o->box(FL_NO_BOX);
          o->labelfont(1);
          o->labelsize(16);
          o->labelcolor((Fl_Color)26);
          o->textsize(16);
          o->textcolor((Fl_Color)26);
        } // Fl_Output* o
        { Fl_Button* o = new Fl_Button(500, 54, 95, 35, "Join");
          o->box(FL_GLEAM_THIN_UP_BOX);
          o->color((Fl_Color)138);
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor((Fl_Color)26);
        } // Fl_Button* o
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Scroll* o
    { Fl_Button* o = new Fl_Button(260, 585, 155, 40, "Refresh");
      o->box(FL_GLEAM_THIN_UP_BOX);
      o->color((Fl_Color)138);
      o->labelfont(1);
      o->labelsize(18);
      o->labelcolor((Fl_Color)26);
    } // Fl_Button* o
    { Fl_Box* o = new Fl_Box(687, 20, 255, 595);
      o->box(FL_GTK_DOWN_BOX);
      o->color(FL_FOREGROUND_COLOR);
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(695, 43, 240, 268);
      o->box(FL_GLEAM_THIN_UP_BOX);
      o->color((Fl_Color)36);
      { Fl_Text_Display* o = new Fl_Text_Display(729, 95, 155, 0, "Player Info");
        o->box(FL_NO_BOX);
        o->labelfont(1);
        o->labelsize(24);
        o->labelcolor((Fl_Color)26);
        o->align(Fl_Align(129));
      } // Fl_Text_Display* o
      { Fl_Output* o = new Fl_Output(818, 105, 102, 29, "Name          ");
        o->box(FL_NO_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
        o->textsize(16);
        o->textcolor((Fl_Color)26);
      } // Fl_Output* o
      { Fl_Output* o = new Fl_Output(818, 130, 102, 30, "Player ID     ");
        o->box(FL_NO_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
        o->textsize(16);
        o->textcolor((Fl_Color)26);
      } // Fl_Output* o
      { Fl_Output* o = new Fl_Output(819, 157, 104, 29, "Balance       ");
        o->box(FL_NO_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
        o->textsize(16);
        o->textcolor((Fl_Color)26);
      } // Fl_Output* o
      { Fl_Output* o = new Fl_Output(821, 183, 94, 28, "Total Games");
        o->box(FL_NO_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
        o->textsize(16);
        o->textcolor((Fl_Color)26);
      } // Fl_Output* o
      { Fl_Output* o = new Fl_Output(819, 208, 100, 29, "Hands won  ");
        o->box(FL_NO_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
        o->textsize(16);
        o->textcolor((Fl_Color)26);
      } // Fl_Output* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(696, 333, 239, 256);
      o->box(FL_GLEAM_THIN_UP_BOX);
      o->color((Fl_Color)36);
      { Fl_Text_Display* o = new Fl_Text_Display(704, 386, 213, 0, "Play style");
        o->box(FL_NO_BOX);
        o->labelfont(1);
        o->labelsize(24);
        o->labelcolor((Fl_Color)26);
        o->align(Fl_Align(129));
      } // Fl_Text_Display* o
      { Fl_Round_Button* o = new Fl_Round_Button(711, 396, 25, 25, " Manual");
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(711, 420, 25, 25, " Basic");
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(711, 443, 25, 25, " Aggressive");
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(711, 466, 25, 25, " Counting");
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(711, 489, 25, 25, " Conservative");
        o->down_box(FL_ROUND_DOWN_BOX);
        o->labelfont(1);
        o->labelsize(16);
        o->labelcolor((Fl_Color)26);
      } // Fl_Round_Button* o
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
