// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "login_view.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(430, 475, "Login");
    w = o;
    { new Fl_Box(0, 0, 430, 475);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(48, 40, 330, 190);
      o->box(FL_GLEAM_UP_BOX);
      o->color(FL_FOREGROUND_COLOR);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(84, 273, 245, 40, "Enter your name:");
      o->box(FL_GLEAM_UP_BOX);
      o->color(FL_FOREGROUND_COLOR);
      o->labelfont(1);
      o->labelsize(20);
      o->labelcolor((Fl_Color)26);
    } // Fl_Box* o
    { Fl_Input* o = new Fl_Input(85, 327, 245, 30);
      o->labelsize(24);
      o->textsize(20);
    } // Fl_Input* o
    { Fl_Button* o = new Fl_Button(154, 380, 105, 33, "Login");
      o->box(FL_GLEAM_UP_BOX);
      o->color((Fl_Color)178);
      o->labelfont(1);
      o->labelsize(18);
      o->labelcolor((Fl_Color)26);
    } // Fl_Button* o
    { Fl_Text_Display* o = new Fl_Text_Display(81, 207, 257, 0, "Welcome to Jack Black\'s BlackJack");
      o->box(FL_NO_BOX);
      o->labeltype(FL_SHADOW_LABEL);
      o->labelfont(3);
      o->labelsize(38);
      o->labelcolor((Fl_Color)26);
      o->align(Fl_Align(129));
    } // Fl_Text_Display* o
    { Fl_Button* o = new Fl_Button(154, 420, 105, 33, "Quit");
      o->box(FL_GLEAM_UP_BOX);
      o->color((Fl_Color)178);
      o->labelfont(1);
      o->labelsize(18);
      o->labelcolor((Fl_Color)26);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
