// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef table_h
#define table_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Spinner.H>
Fl_Double_Window* make_window();
#endif
